<!DOCTYPE html>
<html lang="en">
<head>
<title>Form Information</title>
</head>

<body>
<?php
/* This page receives and handles the data generated by a form.
The predefined $_POST variable is used to collect values from a form sent with method="post".
Information sent from a form with the POST method is invisible to others and has no limits on the amount of information to send. */
print "<h2>Thank You for Writing</h2><br />\n";
print "Your first name is {$_POST['firstname']}.<br />\n";
print "Your last name is {$_POST['lastname']}.<br />\n";
print "Your email is {$_POST['email']}.<br />\n";
print "Your URL is <a href='{$_POST['url']}'> {$_POST['url']}</a>.<br />\n";
print "{$_POST['discipline']} is your profession<br />\n";
print "Your gender is {$_POST['gender']}.<br />\n";
print "Your career interests are:<br />\n {$_POST['response']}<br>\n";
print "Your favorite color is:<br />\n {$_POST['favcolor']}<br>\n";
print "Your security code is:<br />\n {$_POST['security']}<br>\n";
?>

<p>The data above is retrieved from a form filled out by a user and is entirely scripted via PHP on this page</p>
</body>
